language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
  - pip install coveralls
script:
  - export PYTHONPATH=$PYTHONPATH:`pwd`
  - make coverage
after_success:
  - coveralls
